### PR TITLE
Update hook.php

### PR DESCRIPTION
**Pull request by exilitywork**
Categories are changed correct in creation ticketform

### CODE REVIEW

**Comment by joomlafun** [comment]
I do not know if the issue is linked but I get the following error on any group page:
[2020-07-12 09:40:20] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /home/glpi/inc/commondbtm.class.php at line 453

Maybe it is because I use GLPI 9.5?
The "fields" plugin used to have the same issue https://github.com/pluginsGLPI/fields/issues/256

I would appreciate if you could take a look.

Full log : 

[2020-07-12 09:40:20] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /glpi/inc/commondbtm.class.php at line 453
  Backtrace :
  ...ns/groupcategory/inc/groupcategory.class.php:19 CommonDBTM->find()
  plugins/groupcategory/hook.php:56                  PluginGroupcategoryGroupcategory::getAllCategories()
  ...s/groupcategory/inc/groupcategory.class.php:109 plugin_groupcategory_post_show_group()
  inc/plugin.class.php:1286                          PluginGroupcategoryGroupcategory::post_item_form()
  inc/commondbtm.class.php:2406                      Plugin::doHook()
  inc/group.class.php:292                            CommonDBTM->showFormButtons()
  inc/commonglpi.class.php:627                       Group->showForm()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

**Comment by exilitywork** [comment]
I use plugin on GLPI 9.4.5. It has not support 9.5.

**Comment by joomlafun** [comment]
Ok

**Comment by ctresvaux** [comment]
These changes will be resolved in future release

**Pull request closed without merging**
